# Generated by Django 3.1.5 on 2021-01-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreditCardNumber', models.CharField(max_length=1500)),
                ('CardHolder', models.CharField(max_length=1500)),
                ('ExpirationDate', models.DateField()),
                ('SecurityCode', models.CharField(max_length=3)),
                ('Amount', models.FloatField()),
            ],
        ),
    ]
